BOARD_TAG    = mini328
ARDUINO_LIBS =
ARDUINO_PORT = /dev/ttyACM0
USER_LIB_PATH    :=  /home/LukeMcNemee/Arduino/Arduino/lib
CPPFLAGS     = -DID=10 -DGROUP=5 -DPARENTID=2 
include $(ARDUINO_HOME)/Arduino.mk
